version: '3'

services:
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: passwordparaprueba
      MYSQL_DATABASE: demoJwt
      MYSQL_USER: usuarioprueba
      MYSQL_PASSWORD: passwordUser
      MYSQL_ALLOW_CLEARTEXT_PASSWORD: 'yes'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
