version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: passwordparaprueba
      MYSQL_DATABASE: demo
      MYSQL_USER: usuarioprueba
      MYSQL_PASSWORD: passwordUser
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
